package com.example.dag;

import com.example.dag.coverage.*;
import com.example.dag.coverage.ControlRequirementExtractor.*;
import com.example.dag.coverage.CoverageObligationEngine.*;
import com.example.dag.runtime.RuntimeExecutionService;
import com.example.dag.server.GraphWorkspace;
import com.example.dag.testcase.DeterministicTestGenerationService;
import com.example.dag.testcase.DeterministicTestGenerationService.*;
import junit.framework.TestCase;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

public class AdvancedCandidateGenerationTest extends TestCase {
  private final CoverageObligationEngine engine=new CoverageObligationEngine();private final ControlRequirementExtractor extractor=new ControlRequirementExtractor();

  public void testOllamaValidJsonCandidateUsesRuntimeValidation(){GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=obligation(w,Criterion.STATEMENT_CONTROL,"true");var x=unsupported(extractor.extract(w.current(),o));GenerationResult r=service(p->"{\"candidates\":[{\"x\":1}]}").generate(w.current(),o,x,session(w),options());assertRetained(r,"OLLAMA");}
  public void testOllamaInvalidResponse(){GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=obligation(w,Criterion.STATEMENT_CONTROL,"true");GenerationResult r=service(p->"not-json").generate(w.current(),o,unsupported(extractor.extract(w.current(),o)),session(w),options());assertEquals(GenerationStatus.UNSUPPORTED,r.status());assertTrue(r.records().get(0).generationError().contains("Invalid Ollama response"));}
  public void testOllamaUnavailable(){GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=obligation(w,Criterion.STATEMENT_CONTROL,"true");GenerationResult r=service(p->{throw new IllegalStateException("offline");}).generate(w.current(),o,unsupported(extractor.extract(w.current(),o)),session(w),options());assertEquals(GenerationStatus.UNSUPPORTED,r.status());assertTrue(r.reason().contains("unavailable"));}
  public void testDeterministicDoesNotCallOllama(){AtomicInteger calls=new AtomicInteger();GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=obligation(w,Criterion.STATEMENT_CONTROL,"true");GenerationResult r=service(p->{calls.incrementAndGet();throw new AssertionError();}).generate(w.current(),o,extractor.extract(w.current(),o),session(w),options());assertRetained(r,"DETERMINISTIC");assertEquals(0,calls.get());}
  public void testExplicitThrowTarget(){GraphWorkspace w=graph("class A{static void m(boolean fire){try{if(fire)throw new IllegalArgumentException();}catch(IllegalArgumentException e){}}}");assertRetained(generate(w,obligation(w,Criterion.EXCEPTION_THROW_FLOW,null)),"EXCEPTION");}
  public void testArithmeticExceptionTarget(){GraphWorkspace w=graph("class A{static void m(int divisor){try{if(divisor==0)throw new ArithmeticException();}catch(ArithmeticException e){}}}");GenerationResult r=generate(w,obligation(w,Criterion.EXCEPTION_THROW_FLOW,null));assertRetained(r,"EXCEPTION");assertTrue(r.retained().inputs().stream().anyMatch(i->i.javaLiteral().replace("L","").equals("0")));}
  public void testTypedCatchTarget(){GraphWorkspace w=graph("class A{static void m(){try{throw new NumberFormatException();}catch(NumberFormatException e){}}}");assertRetained(generate(w,obligation(w,Criterion.EXCEPTION_CATCH,null)),"EXCEPTION");}
  public void testIncompatibleCatchRejected(){GraphWorkspace w=graph("class A{static void m(){try{throw new IllegalArgumentException();}catch(NullPointerException e){}}}");GenerationResult r=generate(w,obligation(w,Criterion.EXCEPTION_CATCH,null));assertEquals(GenerationStatus.BLOCKED,r.status());assertFalse(r.records().stream().anyMatch(TestCaseRecord::targetMarked));}
  public void testInterproceduralExceptionTarget(){GraphWorkspace w=graph("class A{static void f(){throw new RuntimeException();}static void m(){try{f();}catch(RuntimeException e){}}}");assertRetained(generate(w,obligation(w,Criterion.EXCEPTION_THROW_FLOW,null)),"EXCEPTION");}
  public void testPolymorphicTargetA(){Poly p=poly();Obligation o=polyObligation(p.workspace,"A");assertRetained(generate(p.workspace,o),"POLYMORPHIC");}
  public void testPolymorphicTargetB(){Poly p=poly();Obligation o=polyObligation(p.workspace,"B");GenerationResult r=generate(p.workspace,o);assertRetained(r,"POLYMORPHIC");assertTrue(r.retained().runtimeTarget().startsWith("B."));}
  public void testCumulativePolymorphicTargets(){Poly p=poly();RuntimeCoverageSession s=session(p.workspace);GenerationResult a=generate(p.workspace,polyObligation(p.workspace,"A"),s),b=generate(p.workspace,polyObligation(p.workspace,"B"),s);assertRetained(a,"POLYMORPHIC");assertRetained(b,"POLYMORPHIC");assertEquals(2,s.summarize(nodes(p.workspace),edges(p.workspace)).testCount());}
  public void testInheritedMethodRuntime(){GraphWorkspace w=graph("class P{void f(){}}class C extends P{void run(){f();}}");assertRetained(generate(w,obligation(w,Criterion.METHOD_CALL_EM2,null)),"INHERITED");}
  public void testUnsupportedPolymorphicConstructor(){GraphWorkspace w=graph("class A{void f(){}}class B extends A{private B(){}void f(){}}class T{static void run(A a){a.f();}}");Obligation o=polyObligation(w,"B");GenerationResult r=generate(w,o);assertEquals(GenerationStatus.UNSUPPORTED,r.status());assertTrue(r.reason().contains("constructor"));}
  public void testFailedCandidateRepairStillUsesRuntime(){GraphWorkspace w=graph("class A{static void m(int x){if(0<x){x++;}}}");GenerationResult r=generate(w,obligation(w,Criterion.STATEMENT_CONTROL,"true"));assertRetained(r,"DETERMINISTIC");assertTrue(r.attempts()>1);}
  public void testTargetAcceptedOnlyWhenRuntimeMarked(){GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=obligation(w,Criterion.STATEMENT_CONTROL,"true");GenerationResult r=service(p->"{\"candidates\":[{\"x\":-1}]}").generate(w.current(),o,unsupported(extractor.extract(w.current(),o)),session(w),new Options(1,5000,3000));assertEquals(GenerationStatus.BLOCKED,r.status());assertFalse(r.records().get(0).targetMarked());}
  public void testGenerationLimitRemainsBounded(){GraphWorkspace w=graph("class A{static void m(int x){if(100<x){x++;}}}");Obligation o=obligation(w,Criterion.STATEMENT_CONTROL,"true");GenerationResult r=new DeterministicTestGenerationService().generate(w.current(),o,extractor.extract(w.current(),o),session(w),new Options(1,1000,1000));assertTrue(r.attempts()<=1);}

  private Poly poly(){return new Poly(graph("class A{void f(){}}class B extends A{void f(){}}class T{static void run(A a){a.f();}}"));}
  private Obligation polyObligation(GraphWorkspace w,String target){return catalog(w).obligations().stream().filter(o->o.criterion()==Criterion.POLYMORPHIC_CALL_EM3).filter(o->w.current().graph().nodes().stream().anyMatch(n->n.id().equals(o.details().methodEntryId())&&target.equals(n.classId()))).findFirst().orElseThrow();}
  private GenerationResult generate(GraphWorkspace w,Obligation o){return generate(w,o,session(w));}private GenerationResult generate(GraphWorkspace w,Obligation o,RuntimeCoverageSession s){return new DeterministicTestGenerationService().generate(w.current(),o,extractor.extract(w.current(),o),s,options());}
  private DeterministicTestGenerationService service(OllamaProvider p){return new DeterministicTestGenerationService(new RuntimeExecutionService(),p);}private Options options(){return new Options(12,15000,4000);}
  private Result unsupported(Result r){return new Result(r.graphId(),r.obligationId(),RequirementStatus.UNSUPPORTED,r.requirements());}
  private GraphWorkspace graph(String source){return new GraphWorkspace(List.of(new GraphWorkspace.SourceFile("Test.java",source)));}private Catalog catalog(GraphWorkspace w){return engine.build(w.current(),CoverageAnalyzer.CoverageMarking.staticPrediction(Set.of(),Set.of()),null);}private Obligation obligation(GraphWorkspace w,Criterion c,String branch){return catalog(w).obligations().stream().filter(o->o.criterion()==c&&(branch==null||branch.equals(o.details().requiredBranch()))).findFirst().orElseThrow();}
  private RuntimeCoverageSession session(GraphWorkspace w){return new RuntimeCoverageSession(nodes(w).size(),edges(w).size());}private List<com.example.dag.graph.Node> nodes(GraphWorkspace w){return w.current().builders().stream().flatMap(b->b.getAllNodes().stream()).toList();}private List<com.example.dag.graph.Edge> edges(GraphWorkspace w){return w.current().builders().stream().flatMap(b->b.getAllEdges().stream()).toList();}
  private void assertRetained(GenerationResult r,String method){assertEquals(r.reason(),GenerationStatus.RETAINED,r.status());assertTrue(r.retained().targetMarked());assertEquals(method,r.retained().generationMethod());assertFalse(r.retained().runtimeEvidence().isEmpty());}private record Poly(GraphWorkspace workspace){}
}
