package com.example.dag;

import com.example.dag.coverage.*;
import com.example.dag.coverage.ControlRequirementExtractor.*;
import com.example.dag.export.CanonicalGraphExporter;
import com.example.dag.export.CanonicalGraphExporter.*;
import com.example.dag.server.GraphWorkspace;
import junit.framework.TestCase;
import java.util.*;

public class ControlRequirementExtractorTest extends TestCase {
  private final CoverageObligationEngine obligations=new CoverageObligationEngine();private final ControlRequirementExtractor extractor=new ControlRequirementExtractor();
  public void testSimpleIfTrueTarget(){Result r=extract(graph("class A{void m(int x){if(x>0){x++;}}}"),o(graph("class A{void m(int x){if(x>0){x++;}}}"),CoverageObligationEngine.Criterion.STATEMENT_CONTROL,"true"));assertControl(r,"x>0",Outcome.TRUE);}
  public void testSimpleIfFalseTarget(){GraphWorkspace w=graph("class A{void m(int x){if(x>0){x++;}else{x--;}}}");assertControl(extract(w,o(w,CoverageObligationEngine.Criterion.STATEMENT_CONTROL,"false")),"x>0",Outcome.FALSE);}
  public void testNestedIfIncludesCompleteChain(){GraphWorkspace w=graph("class A{void m(int x,int y){if(x>0){if(y>0){x++;}}}}");Result r=extract(w,inner(w,"true"));assertEquals(List.of("x>0","y>0"),controls(r).stream().map(Requirement::expression).toList());}
  public void testMixedNestedOutcomes(){GraphWorkspace w=graph("class A{void m(int x,int y){if(x>0){if(y>0){x++;}else{x--;}}}}");Result r=extract(w,o(w,CoverageObligationEngine.Criterion.STATEMENT_CONTROL,"false"));assertEquals(List.of(Outcome.TRUE,Outcome.FALSE),controls(r).stream().map(Requirement::requiredOutcome).toList());}
  public void testWhileBodyRequiresTrue(){GraphWorkspace w=graph("class A{void m(int x){while(x>0){x--;}}}");assertControl(extract(w,o(w,CoverageObligationEngine.Criterion.STATEMENT_CONTROL,"true")),"x>0",Outcome.TRUE);}
  public void testLoopExitWhereRepresentedRequiresFalse(){GraphWorkspace w=withLoopExit(graph("class A{void m(int x){while(x>0){x--;}}}"));assertControl(extract(w,o(w,CoverageObligationEngine.Criterion.STATEMENT_CONTROL,"false")),"x>0",Outcome.FALSE);}
  public void testMethodEntryHasOnlyTargetRequirement(){GraphWorkspace w=graph("class A{void m(){}} ");Result r=extract(w,o(w,CoverageObligationEngine.Criterion.METHOD,null));assertEquals(1,r.requirements().size());assertEquals(Kind.TARGET_REQUIREMENT,r.requirements().get(0).kind());}
  public void testMethodCallKeepsOuterControl(){GraphWorkspace w=graph("class A{void f(){}void m(boolean b){if(b){f();}}}");Result r=extract(w,o(w,CoverageObligationEngine.Criterion.METHOD_CALL_EM1,null));assertControl(r,"b",Outcome.TRUE);}
  public void testEm3PreservesTargetAndControl(){GraphWorkspace w=graph("class A{void f(){}}class B extends A{void f(){}}class T{void m(boolean b){if(b){A a=new B();a.f();}}}");Result r=extract(w,o(w,CoverageObligationEngine.Criterion.POLYMORPHIC_CALL_EM3,null));assertControl(r,"b",Outcome.TRUE);assertNotNull(r.requirements().get(r.requirements().size()-1).targetDetails().methodEntryId());}
  public void testEe1PreservesExceptionAndOuterControl(){GraphWorkspace w=graph("class A{void m(boolean b){if(b){try{throw new RuntimeException();}catch(RuntimeException e){}}}} ");Result r=extract(w,o(w,CoverageObligationEngine.Criterion.EXCEPTION_THROW_FLOW,null));assertControl(r,"b",Outcome.TRUE);assertEquals("RuntimeException",target(r).targetDetails().exceptionType());}
  public void testEe2PreservesCatchAndOuterControl(){GraphWorkspace w=graph("class A{void m(boolean b){if(b){try{}catch(RuntimeException e){}}}} ");Result r=extract(w,o(w,CoverageObligationEngine.Criterion.EXCEPTION_CATCH,null));assertControl(r,"b",Outcome.TRUE);assertEquals("RuntimeException",target(r).targetDetails().exceptionType());}
  public void testMissingExpressionIsUnsupported(){GraphWorkspace w=withoutPredicateLine(graph("class A{void m(boolean b){if(b){int x=1;}}}"));Result r=extract(w,o(w,CoverageObligationEngine.Criterion.STATEMENT_CONTROL,"true"));assertEquals(RequirementStatus.UNSUPPORTED,r.status());assertNull(controls(r).get(0).expression());}
  public void testChainOrderIsOutermostToInnermost(){GraphWorkspace w=graph("class A{void m(boolean a,boolean b,boolean c){if(a){if(b){if(c){int x=1;}}}}}");assertEquals(List.of("a","b","c"),controls(extract(w,inner(w,"true"))).stream().map(Requirement::expression).toList());}
  public void testNoSafetyConditionsAreInvented(){GraphWorkspace w=graph("class A{void m(int[][] matrix){if(matrix[1][2]>10){int x=1;}}}");Result r=extract(w,o(w,CoverageObligationEngine.Criterion.STATEMENT_CONTROL,"true"));assertEquals(0,r.requirements().stream().filter(q->q.kind()==Kind.SAFETY_PRECONDITION).count());}
  public void testGraphChangeDoesNotReuseRequirements(){GraphWorkspace a=graph("class A{void m(boolean b){if(b){int x=1;}}}"),b=graph("class A{void m(boolean c){if(c){int x=1;}}}");var old=o(a,CoverageObligationEngine.Criterion.STATEMENT_CONTROL,"true");Result r=extractor.extract(b.current(),old);assertEquals(RequirementStatus.STALE,r.status());}

  private GraphWorkspace graph(String code){return new GraphWorkspace(List.of(new GraphWorkspace.SourceFile("Test.java",code)));}
  private Result extract(GraphWorkspace w,CoverageObligationEngine.Obligation o){return extractor.extract(w.current(),o);}
  private CoverageObligationEngine.Catalog catalog(GraphWorkspace w){return obligations.build(w.current(),CoverageAnalyzer.CoverageMarking.staticPrediction(Set.of(),Set.of()),null);}
  private CoverageObligationEngine.Obligation o(GraphWorkspace w,CoverageObligationEngine.Criterion c,String branch){return catalog(w).obligations().stream().filter(x->x.criterion()==c&&(branch==null||branch.equals(x.details().requiredBranch()))).findFirst().orElseThrow();}
  private CoverageObligationEngine.Obligation inner(GraphWorkspace w,String branch){return catalog(w).obligations().stream().filter(x->x.criterion()==CoverageObligationEngine.Criterion.STATEMENT_CONTROL&&branch.equals(x.details().requiredBranch())).reduce((a,b)->b).orElseThrow();}
  private List<Requirement> controls(Result r){return r.requirements().stream().filter(q->q.kind()==Kind.CONTROL_REQUIREMENT).toList();}private Requirement target(Result r){return r.requirements().stream().filter(q->q.kind()==Kind.TARGET_REQUIREMENT).findFirst().orElseThrow();}
  private void assertControl(Result r,String expression,Outcome outcome){assertEquals(RequirementStatus.SUPPORTED,r.status());assertTrue(controls(r).stream().anyMatch(q->expression.equals(q.expression())&&outcome==q.requiredOutcome()));}
  private GraphWorkspace withLoopExit(GraphWorkspace w){var s=w.current();CanonicalGraph g=s.graph();NodeRecord predicate=g.nodes().stream().filter(n->"LOOP_PREDICATE".equals(n.type())).findFirst().orElseThrow();NodeRecord exit=new NodeRecord(predicate.id()+"-exit","vs1_exit","STMT",predicate.classId(),predicate.methodId(),predicate.file(),predicate.line(),List.of());EdgeRecord edge=new EdgeRecord(predicate.id()+"::ec_exit","ec_exit","CONTROL_DEPENDENCE",predicate.id(),exit.id(),"false",null,List.of());CanonicalGraph changed=new CanonicalGraph(new Metadata(g.metadata().program(),g.metadata().statementCount()+1,g.nodes().size()+1,g.edges().size()+1),append(g.nodes(),exit),append(g.edges(),edge));return replace(w,changed);}
  private GraphWorkspace withoutPredicateLine(GraphWorkspace w){var g=w.current().graph();List<NodeRecord> nodes=g.nodes().stream().map(n->"IF_PREDICATE".equals(n.type())?new NodeRecord(n.id(),n.internalId(),n.type(),n.classId(),n.methodId(),n.file(),null,n.exceptionTypes()):n).toList();return replace(w,new CanonicalGraph(g.metadata(),nodes,g.edges()));}
  private GraphWorkspace replace(GraphWorkspace original,CanonicalGraph graph){var s=original.current();String json=CanonicalGraphExporter.toJson(graph);GraphWorkspace replacement=new GraphWorkspace();try{var field=GraphWorkspace.class.getDeclaredField("current");field.setAccessible(true);field.set(replacement,new GraphWorkspace.Snapshot(s.program(),s.sources(),s.builders(),s.startNodes(),graph,json,s.statistics()));return replacement;}catch(Exception e){throw new AssertionError(e);}}
  private <T> List<T> append(List<T> values,T value){List<T> out=new ArrayList<>(values);out.add(value);return List.copyOf(out);}
}
