package com.example.dag;

import com.example.dag.coverage.*;
import com.example.dag.coverage.ControlRequirementExtractor.*;
import com.example.dag.coverage.CoverageObligationEngine.*;
import com.example.dag.runtime.RuntimeExecutionService;
import com.example.dag.server.GraphWorkspace;
import com.example.dag.testcase.*;
import com.example.dag.testcase.DeterministicTestGenerationService.*;
import com.example.dag.testcase.SmtConstraintSolver.*;
import junit.framework.TestCase;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

public class SmtEscalationTest extends TestCase {
  private final CoverageObligationEngine engine=new CoverageObligationEngine();private final ControlRequirementExtractor extractor=new ControlRequirementExtractor();
  public void testSimpleNumericSatTranslation(){String smt=new SmtConstraintSolver().toSmtLib(new Request(List.of(new Variable("x","int")),List.of(new Constraint("x > 10",true)),100,4,4,4));assertTrue(smt.contains("(> x 10)"));}
  public void testMultiVariableArithmeticTranslation(){String smt=new SmtConstraintSolver().toSmtLib(new Request(List.of(new Variable("x","int"),new Variable("y","int"),new Variable("z","int")),List.of(new Constraint("x>10",true),new Constraint("y==2*x+5",true),new Constraint("z<y",true)),100,8,8,8));assertTrue(smt.contains("(= y (+ (* 2 x) 5))"));assertTrue(smt.contains("(< z y)"));}
  public void testBooleanConstraintTranslation(){String smt=new SmtConstraintSolver().toSmtLib(new Request(List.of(new Variable("a","boolean"),new Variable("b","boolean")),List.of(new Constraint("a && !b",true)),100,4,4,4));assertTrue(smt.contains("(and a (not b))"));}
  public void testUnsatDoesNotBecomeInfeasible(){GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=target(w);GenerationResult r=service(req->new SmtConstraintSolver.Result(SmtConstraintSolver.Status.UNSAT,Map.of(),List.of("(> x 0)","(< x 0)"),1,null),p->{throw new IllegalStateException("offline");}).generate(w.current(),o,unsupported(w,o),session(w),options());assertEquals(GenerationStatus.UNSUPPORTED,r.status());assertTrue(r.records().stream().anyMatch(t->t.smt()!=null&&"UNSAT".equals(t.smt().solverStatus())));}
  public void testUnsupportedExpressionFallsThroughToOllama(){AtomicInteger ollama=new AtomicInteger();GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=target(w);ControlRequirementExtractor.Result extracted=unsupportedWithExpression(w,o,"Math.abs(x)>0");GenerationResult r=service(new SmtConstraintSolver()::solve,p->{ollama.incrementAndGet();return"{\"candidates\":[{\"x\":1}]}";}).generate(w.current(),o,extracted,session(w),options());assertEquals(1,ollama.get());assertEquals("OLLAMA",r.retained().generationMethod());}
  public void testSolverTimeoutFallsThroughSafely(){GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=target(w);GenerationResult r=service(req->new SmtConstraintSolver.Result(SmtConstraintSolver.Status.TIMEOUT,Map.of(),List.of("(> x 0)"),2000,"timeout"),p->{throw new IllegalStateException("offline");}).generate(w.current(),o,unsupported(w,o),session(w),options());assertEquals(GenerationStatus.UNSUPPORTED,r.status());assertTrue(r.records().stream().anyMatch(t->t.smt()!=null&&"TIMEOUT".equals(t.smt().solverStatus())));}
  public void testTypedModelConversion(){GraphWorkspace w=graph("class A{static void m(long x,boolean flag){if(x>10&&flag){x++;}}}");Obligation o=target(w);GenerationResult r=service(req->sat(Map.of("x","11","flag","true"),req),p->{throw new AssertionError();}).generate(w.current(),o,unsupported(w,o),session(w),options());assertRetainedSmt(r);assertTrue(r.retained().inputs().stream().anyMatch(i->i.name().equals("x")&&i.javaLiteral().equals("11L")));assertTrue(r.retained().inputs().stream().anyMatch(i->i.name().equals("flag")&&i.javaLiteral().equals("true")));}
  public void testRuntimeValidationOfSmtCandidate(){GraphWorkspace w=graph("class A{static void m(int x,int y,int z){if(x>10&&y==2*x+5&&z<y){z++;}}}");Obligation o=target(w);GenerationResult r=service(req->sat(Map.of("x","11","y","27","z","26"),req),p->{throw new AssertionError();}).generate(w.current(),o,unsupported(w,o),session(w),options());assertRetainedSmt(r);assertFalse(r.retained().runtimeEvidence().isEmpty());}
  public void testDeterministicGeneratorHasPriority(){AtomicInteger smt=new AtomicInteger(),ollama=new AtomicInteger();GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=target(w);GenerationResult r=service(req->{smt.incrementAndGet();return sat(Map.of("x","1"),req);},p->{ollama.incrementAndGet();return"{}";}).generate(w.current(),o,extractor.extract(w.current(),o),session(w),options());assertEquals("DETERMINISTIC",r.retained().generationMethod());assertEquals(0,smt.get());assertEquals(0,ollama.get());}
  public void testOllamaRemainsFinalFallback(){AtomicInteger smt=new AtomicInteger(),ollama=new AtomicInteger();GraphWorkspace w=graph("class A{static void m(int x){if(x>0){x++;}}}");Obligation o=target(w);GenerationResult r=service(req->{smt.incrementAndGet();return new SmtConstraintSolver.Result(SmtConstraintSolver.Status.UNKNOWN,Map.of(),List.of(),1,"unknown");},p->{ollama.incrementAndGet();return"{\"candidates\":[{\"x\":1}]}";}).generate(w.current(),o,unsupported(w,o),session(w),options());assertEquals(1,smt.get());assertEquals(1,ollama.get());assertEquals("OLLAMA",r.retained().generationMethod());}

  private SmtConstraintSolver.Result sat(Map<String,String> model,Request request){return new SmtConstraintSolver.Result(SmtConstraintSolver.Status.SAT,model,request.constraints().stream().map(Constraint::expression).toList(),1,null);}
  private DeterministicTestGenerationService service(SmtConstraintSolver.Provider smt,OllamaProvider ollama){return new DeterministicTestGenerationService(new RuntimeExecutionService(),ollama,smt);}private Options options(){return new Options(4,5000,3000);}
  private GraphWorkspace graph(String source){return new GraphWorkspace(List.of(new GraphWorkspace.SourceFile("Test.java",source)));}private Obligation target(GraphWorkspace w){return engine.build(w.current(),CoverageAnalyzer.CoverageMarking.staticPrediction(Set.of(),Set.of()),null).obligations().stream().filter(o->o.criterion()==Criterion.STATEMENT_CONTROL&&"true".equals(o.details().requiredBranch())).reduce((a,b)->b).orElseThrow();}
  private ControlRequirementExtractor.Result unsupported(GraphWorkspace w,Obligation o){ControlRequirementExtractor.Result r=extractor.extract(w.current(),o);return new ControlRequirementExtractor.Result(r.graphId(),r.obligationId(),RequirementStatus.UNSUPPORTED,r.requirements());}
  private ControlRequirementExtractor.Result unsupportedWithExpression(GraphWorkspace w,Obligation o,String expression){ControlRequirementExtractor.Result r=extractor.extract(w.current(),o);List<Requirement> requirements=r.requirements().stream().map(q->q.kind()==Kind.CONTROL_REQUIREMENT?new Requirement(q.kind(),expression,q.requiredOutcome(),q.controllerNodeId(),q.controllerEdgeId(),q.depth(),q.source(),List.of("x"),RequirementStatus.UNSUPPORTED,q.targetElementId(),q.targetDetails()):q).toList();return new ControlRequirementExtractor.Result(r.graphId(),r.obligationId(),RequirementStatus.UNSUPPORTED,requirements);}
  private RuntimeCoverageSession session(GraphWorkspace w){return new RuntimeCoverageSession(w.current().graph().nodes().size(),w.current().graph().edges().size());}private void assertRetainedSmt(GenerationResult r){assertEquals(r.reason(),GenerationStatus.RETAINED,r.status());assertEquals("SMT",r.retained().generationMethod());assertTrue(r.retained().targetMarked());assertEquals("SAT",r.retained().smt().solverStatus());}
}
